#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MqttXamarinAndroid.Resource", IsApplication=true)]

namespace MqttXamarinAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int abc_fade_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int abc_fade_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int abc_slide_in_bottom = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int abc_slide_in_top = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int abc_slide_out_bottom = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int abc_slide_out_top = 2131034117;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0d0000
			public const int qos = 2131558400;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000f
			public const int actionBarDivider = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int actionBarItemBackground = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int actionBarSize = 2130771982;
			
			// aapt resource value: 0x7f01000c
			public const int actionBarSplitStyle = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int actionBarStyle = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int actionBarTabBarStyle = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int actionBarTabStyle = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int actionBarTabTextStyle = 2130771977;
			
			// aapt resource value: 0x7f01000d
			public const int actionBarWidgetTheme = 2130771981;
			
			// aapt resource value: 0x7f010016
			public const int actionButtonStyle = 2130771990;
			
			// aapt resource value: 0x7f010047
			public const int actionDropDownStyle = 2130772039;
			
			// aapt resource value: 0x7f01004e
			public const int actionLayout = 2130772046;
			
			// aapt resource value: 0x7f010011
			public const int actionMenuTextAppearance = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int actionMenuTextColor = 2130771986;
			
			// aapt resource value: 0x7f01003c
			public const int actionModeBackground = 2130772028;
			
			// aapt resource value: 0x7f01003b
			public const int actionModeCloseButtonStyle = 2130772027;
			
			// aapt resource value: 0x7f01003e
			public const int actionModeCloseDrawable = 2130772030;
			
			// aapt resource value: 0x7f010040
			public const int actionModeCopyDrawable = 2130772032;
			
			// aapt resource value: 0x7f01003f
			public const int actionModeCutDrawable = 2130772031;
			
			// aapt resource value: 0x7f010044
			public const int actionModeFindDrawable = 2130772036;
			
			// aapt resource value: 0x7f010041
			public const int actionModePasteDrawable = 2130772033;
			
			// aapt resource value: 0x7f010046
			public const int actionModePopupWindowStyle = 2130772038;
			
			// aapt resource value: 0x7f010042
			public const int actionModeSelectAllDrawable = 2130772034;
			
			// aapt resource value: 0x7f010043
			public const int actionModeShareDrawable = 2130772035;
			
			// aapt resource value: 0x7f01003d
			public const int actionModeSplitBackground = 2130772029;
			
			// aapt resource value: 0x7f01003a
			public const int actionModeStyle = 2130772026;
			
			// aapt resource value: 0x7f010045
			public const int actionModeWebSearchDrawable = 2130772037;
			
			// aapt resource value: 0x7f01000a
			public const int actionOverflowButtonStyle = 2130771978;
			
			// aapt resource value: 0x7f010050
			public const int actionProviderClass = 2130772048;
			
			// aapt resource value: 0x7f01004f
			public const int actionViewClass = 2130772047;
			
			// aapt resource value: 0x7f01006c
			public const int activityChooserViewStyle = 2130772076;
			
			// aapt resource value: 0x7f01002f
			public const int background = 2130772015;
			
			// aapt resource value: 0x7f010031
			public const int backgroundSplit = 2130772017;
			
			// aapt resource value: 0x7f010030
			public const int backgroundStacked = 2130772016;
			
			// aapt resource value: 0x7f010018
			public const int buttonBarButtonStyle = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int buttonBarStyle = 2130771991;
			
			// aapt resource value: 0x7f010032
			public const int customNavigationLayout = 2130772018;
			
			// aapt resource value: 0x7f010054
			public const int disableChildrenWhenDisabled = 2130772052;
			
			// aapt resource value: 0x7f010028
			public const int displayOptions = 2130772008;
			
			// aapt resource value: 0x7f01002e
			public const int divider = 2130772014;
			
			// aapt resource value: 0x7f01001b
			public const int dividerHorizontal = 2130771995;
			
			// aapt resource value: 0x7f010056
			public const int dividerPadding = 2130772054;
			
			// aapt resource value: 0x7f01001a
			public const int dividerVertical = 2130771994;
			
			// aapt resource value: 0x7f010021
			public const int dropDownListViewStyle = 2130772001;
			
			// aapt resource value: 0x7f010048
			public const int dropdownListPreferredItemHeight = 2130772040;
			
			// aapt resource value: 0x7f01006b
			public const int expandActivityOverflowButtonDrawable = 2130772075;
			
			// aapt resource value: 0x7f010026
			public const int height = 2130772006;
			
			// aapt resource value: 0x7f010013
			public const int homeAsUpIndicator = 2130771987;
			
			// aapt resource value: 0x7f010033
			public const int homeLayout = 2130772019;
			
			// aapt resource value: 0x7f01002c
			public const int icon = 2130772012;
			
			// aapt resource value: 0x7f01005a
			public const int iconifiedByDefault = 2130772058;
			
			// aapt resource value: 0x7f010035
			public const int indeterminateProgressStyle = 2130772021;
			
			// aapt resource value: 0x7f01006a
			public const int initialActivityCount = 2130772074;
			
			// aapt resource value: 0x7f010059
			public const int isLightTheme = 2130772057;
			
			// aapt resource value: 0x7f010037
			public const int itemPadding = 2130772023;
			
			// aapt resource value: 0x7f01004c
			public const int listChoiceBackgroundIndicator = 2130772044;
			
			// aapt resource value: 0x7f010022
			public const int listPopupWindowStyle = 2130772002;
			
			// aapt resource value: 0x7f01001c
			public const int listPreferredItemHeight = 2130771996;
			
			// aapt resource value: 0x7f01001e
			public const int listPreferredItemHeightLarge = 2130771998;
			
			// aapt resource value: 0x7f01001d
			public const int listPreferredItemHeightSmall = 2130771997;
			
			// aapt resource value: 0x7f01001f
			public const int listPreferredItemPaddingLeft = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int listPreferredItemPaddingRight = 2130772000;
			
			// aapt resource value: 0x7f01002d
			public const int logo = 2130772013;
			
			// aapt resource value: 0x7f010027
			public const int navigationMode = 2130772007;
			
			// aapt resource value: 0x7f010039
			public const int paddingEnd = 2130772025;
			
			// aapt resource value: 0x7f010038
			public const int paddingStart = 2130772024;
			
			// aapt resource value: 0x7f01004b
			public const int panelMenuListTheme = 2130772043;
			
			// aapt resource value: 0x7f01004a
			public const int panelMenuListWidth = 2130772042;
			
			// aapt resource value: 0x7f010049
			public const int popupMenuStyle = 2130772041;
			
			// aapt resource value: 0x7f010053
			public const int popupPromptView = 2130772051;
			
			// aapt resource value: 0x7f010036
			public const int progressBarPadding = 2130772022;
			
			// aapt resource value: 0x7f010034
			public const int progressBarStyle = 2130772020;
			
			// aapt resource value: 0x7f010051
			public const int prompt = 2130772049;
			
			// aapt resource value: 0x7f01005b
			public const int queryHint = 2130772059;
			
			// aapt resource value: 0x7f01005c
			public const int searchDropdownBackground = 2130772060;
			
			// aapt resource value: 0x7f010065
			public const int searchResultListItemHeight = 2130772069;
			
			// aapt resource value: 0x7f010069
			public const int searchViewAutoCompleteTextView = 2130772073;
			
			// aapt resource value: 0x7f01005d
			public const int searchViewCloseIcon = 2130772061;
			
			// aapt resource value: 0x7f010061
			public const int searchViewEditQuery = 2130772065;
			
			// aapt resource value: 0x7f010062
			public const int searchViewEditQueryBackground = 2130772066;
			
			// aapt resource value: 0x7f01005e
			public const int searchViewGoIcon = 2130772062;
			
			// aapt resource value: 0x7f01005f
			public const int searchViewSearchIcon = 2130772063;
			
			// aapt resource value: 0x7f010063
			public const int searchViewTextField = 2130772067;
			
			// aapt resource value: 0x7f010064
			public const int searchViewTextFieldRight = 2130772068;
			
			// aapt resource value: 0x7f010060
			public const int searchViewVoiceIcon = 2130772064;
			
			// aapt resource value: 0x7f010019
			public const int selectableItemBackground = 2130771993;
			
			// aapt resource value: 0x7f01004d
			public const int showAsAction = 2130772045;
			
			// aapt resource value: 0x7f010055
			public const int showDividers = 2130772053;
			
			// aapt resource value: 0x7f010058
			public const int spinnerDropDownItemStyle = 2130772056;
			
			// aapt resource value: 0x7f010052
			public const int spinnerMode = 2130772050;
			
			// aapt resource value: 0x7f010057
			public const int spinnerStyle = 2130772055;
			
			// aapt resource value: 0x7f010029
			public const int subtitle = 2130772009;
			
			// aapt resource value: 0x7f01002b
			public const int subtitleTextStyle = 2130772011;
			
			// aapt resource value: 0x7f01006d
			public const int textAllCaps = 2130772077;
			
			// aapt resource value: 0x7f010014
			public const int textAppearanceLargePopupMenu = 2130771988;
			
			// aapt resource value: 0x7f010023
			public const int textAppearanceListItem = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int textAppearanceListItemSmall = 2130772004;
			
			// aapt resource value: 0x7f010067
			public const int textAppearanceSearchResultSubtitle = 2130772071;
			
			// aapt resource value: 0x7f010066
			public const int textAppearanceSearchResultTitle = 2130772070;
			
			// aapt resource value: 0x7f010015
			public const int textAppearanceSmallPopupMenu = 2130771989;
			
			// aapt resource value: 0x7f010068
			public const int textColorSearchUrl = 2130772072;
			
			// aapt resource value: 0x7f010025
			public const int title = 2130772005;
			
			// aapt resource value: 0x7f01002a
			public const int titleTextStyle = 2130772010;
			
			// aapt resource value: 0x7f010000
			public const int windowActionBar = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int windowActionBarOverlay = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int windowFixedHeightMajor = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int windowFixedHeightMinor = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int windowFixedWidthMajor = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int windowFixedWidthMinor = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int windowSplitActionBar = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int abc_action_bar_embed_tabs_pre_jb = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int abc_action_bar_expanded_action_views_exclusive = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int abc_config_actionMenuItemAllCaps = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int abc_config_allowActionMenuItemTextWithIcon = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int abc_config_showMenuShortcutsWhenKeyboardPresent = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int abc_split_action_bar_is_narrow = 2131099650;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int abc_search_url_text_holo = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int abc_search_url_text_normal = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int abc_search_url_text_pressed = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int abc_search_url_text_selected = 2131165185;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080002
			public const int abc_action_bar_default_height = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int abc_action_bar_icon_vertical_padding = 2131230723;
			
			// aapt resource value: 0x7f08000a
			public const int abc_action_bar_progress_bar_size = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int abc_action_bar_stacked_max_height = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int abc_action_bar_stacked_tab_max_width = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int abc_action_bar_subtitle_bottom_margin = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int abc_action_bar_subtitle_text_size = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int abc_action_bar_subtitle_top_margin = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int abc_action_bar_title_text_size = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int abc_action_button_min_width = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int abc_config_prefDialogWidth = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int abc_dropdownitem_icon_width = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int abc_dropdownitem_text_padding_left = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int abc_dropdownitem_text_padding_right = 2131230735;
			
			// aapt resource value: 0x7f08000b
			public const int abc_panel_menu_list_width = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int abc_search_view_preferred_width = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int abc_search_view_text_min_width = 2131230732;
			
			// aapt resource value: 0x7f080013
			public const int dialog_fixed_height_major = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int dialog_fixed_height_minor = 2131230740;
			
			// aapt resource value: 0x7f080011
			public const int dialog_fixed_width_major = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int dialog_fixed_width_minor = 2131230738;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abc_ab_bottom_solid_dark_holo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int abc_ab_bottom_solid_light_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int abc_ab_bottom_transparent_dark_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int abc_ab_bottom_transparent_light_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int abc_ab_share_pack_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int abc_ab_share_pack_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int abc_ab_solid_dark_holo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int abc_ab_solid_light_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int abc_ab_stacked_solid_dark_holo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int abc_ab_stacked_solid_light_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int abc_ab_stacked_transparent_dark_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int abc_ab_stacked_transparent_light_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int abc_ab_transparent_dark_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int abc_ab_transparent_light_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int abc_cab_background_bottom_holo_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int abc_cab_background_bottom_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int abc_cab_background_top_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int abc_cab_background_top_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int abc_ic_ab_back_holo_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int abc_ic_ab_back_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int abc_ic_cab_done_holo_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int abc_ic_cab_done_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int abc_ic_clear = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int abc_ic_clear_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int abc_ic_clear_holo_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int abc_ic_clear_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int abc_ic_clear_search_api_disabled_holo_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int abc_ic_clear_search_api_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int abc_ic_commit_search_api_holo_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int abc_ic_commit_search_api_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int abc_ic_go = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int abc_ic_go_search_api_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int abc_ic_menu_moreoverflow_normal_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int abc_ic_menu_moreoverflow_normal_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int abc_ic_menu_share_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int abc_ic_menu_share_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int abc_ic_search = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int abc_ic_search_api_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int abc_ic_voice_search = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int abc_ic_voice_search_api_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int abc_item_background_holo_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int abc_item_background_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int abc_list_divider_holo_dark = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int abc_list_divider_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int abc_list_focused_holo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int abc_list_longpressed_holo = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int abc_list_pressed_holo_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int abc_list_pressed_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int abc_list_selector_background_transition_holo_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int abc_list_selector_background_transition_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int abc_list_selector_disabled_holo_dark = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int abc_list_selector_disabled_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int abc_list_selector_holo_dark = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int abc_list_selector_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int abc_menu_dropdown_panel_holo_dark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int abc_menu_dropdown_panel_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int abc_menu_hardkey_panel_holo_dark = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int abc_menu_hardkey_panel_holo_light = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int abc_search_dropdown_dark = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int abc_search_dropdown_light = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int abc_spinner_ab_default_holo_dark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int abc_spinner_ab_default_holo_light = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int abc_spinner_ab_disabled_holo_dark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int abc_spinner_ab_disabled_holo_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int abc_spinner_ab_focused_holo_dark = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int abc_spinner_ab_focused_holo_light = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int abc_spinner_ab_holo_dark = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int abc_spinner_ab_holo_light = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int abc_spinner_ab_pressed_holo_dark = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int abc_spinner_ab_pressed_holo_light = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int abc_tab_indicator_ab_holo = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int abc_tab_selected_focused_holo = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int abc_tab_selected_holo = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int abc_tab_selected_pressed_holo = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int abc_tab_unselected_pressed_holo = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int abc_textfield_search_default_holo_dark = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int abc_textfield_search_default_holo_light = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int abc_textfield_search_right_default_holo_dark = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int abc_textfield_search_right_default_holo_light = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int abc_textfield_search_right_selected_holo_dark = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int abc_textfield_search_right_selected_holo_light = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int abc_textfield_search_selected_holo_dark = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int abc_textfield_search_selected_holo_light = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int abc_textfield_searchview_holo_dark = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int abc_textfield_searchview_holo_light = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int abc_textfield_searchview_right_holo_dark = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int abc_textfield_searchview_right_holo_light = 2130837590;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001c
			public const int action_bar = 2131361820;
			
			// aapt resource value: 0x7f0a0001
			public const int action_bar_activity_content = 2131361793;
			
			// aapt resource value: 0x7f0a001b
			public const int action_bar_container = 2131361819;
			
			// aapt resource value: 0x7f0a001f
			public const int action_bar_overlay_layout = 2131361823;
			
			// aapt resource value: 0x7f0a001a
			public const int action_bar_root = 2131361818;
			
			// aapt resource value: 0x7f0a0023
			public const int action_bar_subtitle = 2131361827;
			
			// aapt resource value: 0x7f0a0022
			public const int action_bar_title = 2131361826;
			
			// aapt resource value: 0x7f0a001d
			public const int action_context_bar = 2131361821;
			
			// aapt resource value: 0x7f0a0002
			public const int action_menu_divider = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int action_menu_presenter = 2131361795;
			
			// aapt resource value: 0x7f0a0024
			public const int action_mode_close_button = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int activity_chooser_view_content = 2131361829;
			
			// aapt resource value: 0x7f0a000f
			public const int always = 2131361807;
			
			// aapt resource value: 0x7f0a0016
			public const int beginning = 2131361814;
			
			// aapt resource value: 0x7f0a0041
			public const int bttConnect = 2131361857;
			
			// aapt resource value: 0x7f0a0046
			public const int bttPublishMes = 2131361862;
			
			// aapt resource value: 0x7f0a0044
			public const int bttSubTopic = 2131361860;
			
			// aapt resource value: 0x7f0a003e
			public const int cbxUser = 2131361854;
			
			// aapt resource value: 0x7f0a002d
			public const int checkbox = 2131361837;
			
			// aapt resource value: 0x7f0a0010
			public const int collapseActionView = 2131361808;
			
			// aapt resource value: 0x7f0a0028
			public const int default_activity_button = 2131361832;
			
			// aapt resource value: 0x7f0a0014
			public const int dialog = 2131361812;
			
			// aapt resource value: 0x7f0a0009
			public const int disableHome = 2131361801;
			
			// aapt resource value: 0x7f0a0015
			public const int dropdown = 2131361813;
			
			// aapt resource value: 0x7f0a0030
			public const int edit_query = 2131361840;
			
			// aapt resource value: 0x7f0a003c
			public const int edtBroker = 2131361852;
			
			// aapt resource value: 0x7f0a0045
			public const int edtMessage = 2131361861;
			
			// aapt resource value: 0x7f0a0040
			public const int edtPassword = 2131361856;
			
			// aapt resource value: 0x7f0a003d
			public const int edtPort = 2131361853;
			
			// aapt resource value: 0x7f0a0042
			public const int edtTopic = 2131361858;
			
			// aapt resource value: 0x7f0a003f
			public const int edtUser = 2131361855;
			
			// aapt resource value: 0x7f0a0017
			public const int end = 2131361815;
			
			// aapt resource value: 0x7f0a0026
			public const int expand_activities_button = 2131361830;
			
			// aapt resource value: 0x7f0a002c
			public const int expanded_menu = 2131361836;
			
			// aapt resource value: 0x7f0a0000
			public const int home = 2131361792;
			
			// aapt resource value: 0x7f0a000a
			public const int homeAsUp = 2131361802;
			
			// aapt resource value: 0x7f0a002a
			public const int icon = 2131361834;
			
			// aapt resource value: 0x7f0a0011
			public const int ifRoom = 2131361809;
			
			// aapt resource value: 0x7f0a0027
			public const int image = 2131361831;
			
			// aapt resource value: 0x7f0a0006
			public const int listMode = 2131361798;
			
			// aapt resource value: 0x7f0a0029
			public const int list_item = 2131361833;
			
			// aapt resource value: 0x7f0a0018
			public const int middle = 2131361816;
			
			// aapt resource value: 0x7f0a0012
			public const int never = 2131361810;
			
			// aapt resource value: 0x7f0a0019
			public const int none = 2131361817;
			
			// aapt resource value: 0x7f0a0007
			public const int normal = 2131361799;
			
			// aapt resource value: 0x7f0a0004
			public const int progress_circular = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int progress_horizontal = 2131361797;
			
			// aapt resource value: 0x7f0a002f
			public const int radio = 2131361839;
			
			// aapt resource value: 0x7f0a0047
			public const int result = 2131361863;
			
			// aapt resource value: 0x7f0a0032
			public const int search_badge = 2131361842;
			
			// aapt resource value: 0x7f0a0031
			public const int search_bar = 2131361841;
			
			// aapt resource value: 0x7f0a0033
			public const int search_button = 2131361843;
			
			// aapt resource value: 0x7f0a0038
			public const int search_close_btn = 2131361848;
			
			// aapt resource value: 0x7f0a0034
			public const int search_edit_frame = 2131361844;
			
			// aapt resource value: 0x7f0a003a
			public const int search_go_btn = 2131361850;
			
			// aapt resource value: 0x7f0a0035
			public const int search_mag_icon = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int search_plate = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int search_src_text = 2131361847;
			
			// aapt resource value: 0x7f0a003b
			public const int search_voice_btn = 2131361851;
			
			// aapt resource value: 0x7f0a002e
			public const int shortcut = 2131361838;
			
			// aapt resource value: 0x7f0a000b
			public const int showCustom = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int showHome = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int showTitle = 2131361805;
			
			// aapt resource value: 0x7f0a001e
			public const int split_action_bar = 2131361822;
			
			// aapt resource value: 0x7f0a0043
			public const int spnQOS = 2131361859;
			
			// aapt resource value: 0x7f0a0039
			public const int submit_area = 2131361849;
			
			// aapt resource value: 0x7f0a0008
			public const int tabMode = 2131361800;
			
			// aapt resource value: 0x7f0a002b
			public const int title = 2131361835;
			
			// aapt resource value: 0x7f0a0020
			public const int top_action_bar = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int up = 2131361825;
			
			// aapt resource value: 0x7f0a000e
			public const int useLogo = 2131361806;
			
			// aapt resource value: 0x7f0a0013
			public const int withText = 2131361811;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_max_action_buttons = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int abc_action_bar_decor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int abc_action_bar_decor_include = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int abc_action_bar_decor_overlay = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int abc_action_bar_home = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int abc_action_bar_tab = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int abc_action_bar_tabbar = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int abc_action_bar_title_item = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int abc_action_bar_view_list_nav_layout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int abc_action_menu_item_layout = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int abc_action_menu_layout = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int abc_action_mode_bar = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int abc_action_mode_close_item = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int abc_activity_chooser_view = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int abc_activity_chooser_view_include = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int abc_activity_chooser_view_list_item = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int abc_expanded_menu_layout = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int abc_list_menu_item_checkbox = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int abc_list_menu_item_icon = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int abc_list_menu_item_layout = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int abc_list_menu_item_radio = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int abc_popup_menu_item_layout = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int abc_search_dropdown_item_icons_2line = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int abc_search_view = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int abc_simple_decor = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int Main = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int support_simple_spinner_dropdown_item = 2130968601;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b0001
			public const int abc_action_bar_home_description = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int abc_action_bar_up_description = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int abc_action_menu_overflow_description = 2131427331;
			
			// aapt resource value: 0x7f0b0000
			public const int abc_action_mode_done = 2131427328;
			
			// aapt resource value: 0x7f0b000a
			public const int abc_activity_chooser_view_see_all = 2131427338;
			
			// aapt resource value: 0x7f0b0009
			public const int abc_activitychooserview_choose_application = 2131427337;
			
			// aapt resource value: 0x7f0b0006
			public const int abc_searchview_description_clear = 2131427334;
			
			// aapt resource value: 0x7f0b0005
			public const int abc_searchview_description_query = 2131427333;
			
			// aapt resource value: 0x7f0b0004
			public const int abc_searchview_description_search = 2131427332;
			
			// aapt resource value: 0x7f0b0007
			public const int abc_searchview_description_submit = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int abc_searchview_description_voice = 2131427336;
			
			// aapt resource value: 0x7f0b000c
			public const int abc_shareactionprovider_share_with = 2131427340;
			
			// aapt resource value: 0x7f0b000b
			public const int abc_shareactionprovider_share_with_application = 2131427339;
			
			// aapt resource value: 0x7f0b000e
			public const int app_name = 2131427342;
			
			// aapt resource value: 0x7f0b000d
			public const int hello = 2131427341;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0c0063
			public const int TextAppearance_AppCompat_Base_CompactMenu_Dialog = 2131492963;
			
			// aapt resource value: 0x7f0c006d
			public const int TextAppearance_AppCompat_Base_SearchResult = 2131492973;
			
			// aapt resource value: 0x7f0c006f
			public const int TextAppearance_AppCompat_Base_SearchResult_Subtitle = 2131492975;
			
			// aapt resource value: 0x7f0c006e
			public const int TextAppearance_AppCompat_Base_SearchResult_Title = 2131492974;
			
			// aapt resource value: 0x7f0c0069
			public const int TextAppearance_AppCompat_Base_Widget_PopupMenu_Large = 2131492969;
			
			// aapt resource value: 0x7f0c006a
			public const int TextAppearance_AppCompat_Base_Widget_PopupMenu_Small = 2131492970;
			
			// aapt resource value: 0x7f0c0070
			public const int TextAppearance_AppCompat_Light_Base_SearchResult = 2131492976;
			
			// aapt resource value: 0x7f0c0072
			public const int TextAppearance_AppCompat_Light_Base_SearchResult_Subtitle = 2131492978;
			
			// aapt resource value: 0x7f0c0071
			public const int TextAppearance_AppCompat_Light_Base_SearchResult_Title = 2131492977;
			
			// aapt resource value: 0x7f0c006b
			public const int TextAppearance_AppCompat_Light_Base_Widget_PopupMenu_Large = 2131492971;
			
			// aapt resource value: 0x7f0c006c
			public const int TextAppearance_AppCompat_Light_Base_Widget_PopupMenu_Small = 2131492972;
			
			// aapt resource value: 0x7f0c0035
			public const int TextAppearance_AppCompat_Light_SearchResult_Subtitle = 2131492917;
			
			// aapt resource value: 0x7f0c0034
			public const int TextAppearance_AppCompat_Light_SearchResult_Title = 2131492916;
			
			// aapt resource value: 0x7f0c0030
			public const int TextAppearance_AppCompat_Light_Widget_PopupMenu_Large = 2131492912;
			
			// aapt resource value: 0x7f0c0031
			public const int TextAppearance_AppCompat_Light_Widget_PopupMenu_Small = 2131492913;
			
			// aapt resource value: 0x7f0c0033
			public const int TextAppearance_AppCompat_SearchResult_Subtitle = 2131492915;
			
			// aapt resource value: 0x7f0c0032
			public const int TextAppearance_AppCompat_SearchResult_Title = 2131492914;
			
			// aapt resource value: 0x7f0c001a
			public const int TextAppearance_AppCompat_Widget_ActionBar_Menu = 2131492890;
			
			// aapt resource value: 0x7f0c0006
			public const int TextAppearance_AppCompat_Widget_ActionBar_Subtitle = 2131492870;
			
			// aapt resource value: 0x7f0c0008
			public const int TextAppearance_AppCompat_Widget_ActionBar_Subtitle_Inverse = 2131492872;
			
			// aapt resource value: 0x7f0c0005
			public const int TextAppearance_AppCompat_Widget_ActionBar_Title = 2131492869;
			
			// aapt resource value: 0x7f0c0007
			public const int TextAppearance_AppCompat_Widget_ActionBar_Title_Inverse = 2131492871;
			
			// aapt resource value: 0x7f0c001e
			public const int TextAppearance_AppCompat_Widget_ActionMode_Subtitle = 2131492894;
			
			// aapt resource value: 0x7f0c0020
			public const int TextAppearance_AppCompat_Widget_ActionMode_Subtitle_Inverse = 2131492896;
			
			// aapt resource value: 0x7f0c001d
			public const int TextAppearance_AppCompat_Widget_ActionMode_Title = 2131492893;
			
			// aapt resource value: 0x7f0c001f
			public const int TextAppearance_AppCompat_Widget_ActionMode_Title_Inverse = 2131492895;
			
			// aapt resource value: 0x7f0c0054
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Menu = 2131492948;
			
			// aapt resource value: 0x7f0c0056
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Subtitle = 2131492950;
			
			// aapt resource value: 0x7f0c0058
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Subtitle_Inverse = 2131492952;
			
			// aapt resource value: 0x7f0c0055
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Title = 2131492949;
			
			// aapt resource value: 0x7f0c0057
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Title_Inverse = 2131492951;
			
			// aapt resource value: 0x7f0c0051
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Subtitle = 2131492945;
			
			// aapt resource value: 0x7f0c0053
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Subtitle_Inverse = 2131492947;
			
			// aapt resource value: 0x7f0c0050
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Title = 2131492944;
			
			// aapt resource value: 0x7f0c0052
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Title_Inverse = 2131492946;
			
			// aapt resource value: 0x7f0c0061
			public const int TextAppearance_AppCompat_Widget_Base_DropDownItem = 2131492961;
			
			// aapt resource value: 0x7f0c0021
			public const int TextAppearance_AppCompat_Widget_DropDownItem = 2131492897;
			
			// aapt resource value: 0x7f0c002e
			public const int TextAppearance_AppCompat_Widget_PopupMenu_Large = 2131492910;
			
			// aapt resource value: 0x7f0c002f
			public const int TextAppearance_AppCompat_Widget_PopupMenu_Small = 2131492911;
			
			// aapt resource value: 0x7f0c0062
			public const int TextAppearance_Widget_AppCompat_Base_ExpandedMenu_Item = 2131492962;
			
			// aapt resource value: 0x7f0c0028
			public const int TextAppearance_Widget_AppCompat_ExpandedMenu_Item = 2131492904;
			
			// aapt resource value: 0x7f0c0077
			public const int Theme_AppCompat = 2131492983;
			
			// aapt resource value: 0x7f0c0083
			public const int Theme_AppCompat_Base_CompactMenu = 2131492995;
			
			// aapt resource value: 0x7f0c0084
			public const int Theme_AppCompat_Base_CompactMenu_Dialog = 2131492996;
			
			// aapt resource value: 0x7f0c007c
			public const int Theme_AppCompat_CompactMenu = 2131492988;
			
			// aapt resource value: 0x7f0c007d
			public const int Theme_AppCompat_CompactMenu_Dialog = 2131492989;
			
			// aapt resource value: 0x7f0c007a
			public const int Theme_AppCompat_DialogWhenLarge = 2131492986;
			
			// aapt resource value: 0x7f0c0078
			public const int Theme_AppCompat_Light = 2131492984;
			
			// aapt resource value: 0x7f0c0079
			public const int Theme_AppCompat_Light_DarkActionBar = 2131492985;
			
			// aapt resource value: 0x7f0c007b
			public const int Theme_AppCompat_Light_DialogWhenLarge = 2131492987;
			
			// aapt resource value: 0x7f0c007e
			public const int Theme_Base = 2131492990;
			
			// aapt resource value: 0x7f0c0080
			public const int Theme_Base_AppCompat = 2131492992;
			
			// aapt resource value: 0x7f0c0087
			public const int Theme_Base_AppCompat_Dialog_FixedSize = 2131492999;
			
			// aapt resource value: 0x7f0c0088
			public const int Theme_Base_AppCompat_Dialog_Light_FixedSize = 2131493000;
			
			// aapt resource value: 0x7f0c0085
			public const int Theme_Base_AppCompat_DialogWhenLarge = 2131492997;
			
			// aapt resource value: 0x7f0c0089
			public const int Theme_Base_AppCompat_DialogWhenLarge_Base = 2131493001;
			
			// aapt resource value: 0x7f0c0081
			public const int Theme_Base_AppCompat_Light = 2131492993;
			
			// aapt resource value: 0x7f0c0082
			public const int Theme_Base_AppCompat_Light_DarkActionBar = 2131492994;
			
			// aapt resource value: 0x7f0c0086
			public const int Theme_Base_AppCompat_Light_DialogWhenLarge = 2131492998;
			
			// aapt resource value: 0x7f0c008a
			public const int Theme_Base_AppCompat_Light_DialogWhenLarge_Base = 2131493002;
			
			// aapt resource value: 0x7f0c007f
			public const int Theme_Base_Light = 2131492991;
			
			// aapt resource value: 0x7f0c0000
			public const int Widget_AppCompat_ActionBar = 2131492864;
			
			// aapt resource value: 0x7f0c0002
			public const int Widget_AppCompat_ActionBar_Solid = 2131492866;
			
			// aapt resource value: 0x7f0c0011
			public const int Widget_AppCompat_ActionBar_TabBar = 2131492881;
			
			// aapt resource value: 0x7f0c0017
			public const int Widget_AppCompat_ActionBar_TabText = 2131492887;
			
			// aapt resource value: 0x7f0c0014
			public const int Widget_AppCompat_ActionBar_TabView = 2131492884;
			
			// aapt resource value: 0x7f0c000b
			public const int Widget_AppCompat_ActionButton = 2131492875;
			
			// aapt resource value: 0x7f0c000d
			public const int Widget_AppCompat_ActionButton_CloseMode = 2131492877;
			
			// aapt resource value: 0x7f0c000f
			public const int Widget_AppCompat_ActionButton_Overflow = 2131492879;
			
			// aapt resource value: 0x7f0c001b
			public const int Widget_AppCompat_ActionMode = 2131492891;
			
			// aapt resource value: 0x7f0c0038
			public const int Widget_AppCompat_ActivityChooserView = 2131492920;
			
			// aapt resource value: 0x7f0c0036
			public const int Widget_AppCompat_AutoCompleteTextView = 2131492918;
			
			// aapt resource value: 0x7f0c003a
			public const int Widget_AppCompat_Base_ActionBar = 2131492922;
			
			// aapt resource value: 0x7f0c003c
			public const int Widget_AppCompat_Base_ActionBar_Solid = 2131492924;
			
			// aapt resource value: 0x7f0c0045
			public const int Widget_AppCompat_Base_ActionBar_TabBar = 2131492933;
			
			// aapt resource value: 0x7f0c004b
			public const int Widget_AppCompat_Base_ActionBar_TabText = 2131492939;
			
			// aapt resource value: 0x7f0c0048
			public const int Widget_AppCompat_Base_ActionBar_TabView = 2131492936;
			
			// aapt resource value: 0x7f0c003f
			public const int Widget_AppCompat_Base_ActionButton = 2131492927;
			
			// aapt resource value: 0x7f0c0041
			public const int Widget_AppCompat_Base_ActionButton_CloseMode = 2131492929;
			
			// aapt resource value: 0x7f0c0043
			public const int Widget_AppCompat_Base_ActionButton_Overflow = 2131492931;
			
			// aapt resource value: 0x7f0c004e
			public const int Widget_AppCompat_Base_ActionMode = 2131492942;
			
			// aapt resource value: 0x7f0c0075
			public const int Widget_AppCompat_Base_ActivityChooserView = 2131492981;
			
			// aapt resource value: 0x7f0c0073
			public const int Widget_AppCompat_Base_AutoCompleteTextView = 2131492979;
			
			// aapt resource value: 0x7f0c005d
			public const int Widget_AppCompat_Base_DropDownItem_Spinner = 2131492957;
			
			// aapt resource value: 0x7f0c0065
			public const int Widget_AppCompat_Base_ListPopupWindow = 2131492965;
			
			// aapt resource value: 0x7f0c005f
			public const int Widget_AppCompat_Base_ListView_DropDown = 2131492959;
			
			// aapt resource value: 0x7f0c0064
			public const int Widget_AppCompat_Base_ListView_Menu = 2131492964;
			
			// aapt resource value: 0x7f0c0067
			public const int Widget_AppCompat_Base_PopupMenu = 2131492967;
			
			// aapt resource value: 0x7f0c005a
			public const int Widget_AppCompat_Base_ProgressBar = 2131492954;
			
			// aapt resource value: 0x7f0c0059
			public const int Widget_AppCompat_Base_ProgressBar_Horizontal = 2131492953;
			
			// aapt resource value: 0x7f0c005b
			public const int Widget_AppCompat_Base_Spinner = 2131492955;
			
			// aapt resource value: 0x7f0c0024
			public const int Widget_AppCompat_DropDownItem_Spinner = 2131492900;
			
			// aapt resource value: 0x7f0c0001
			public const int Widget_AppCompat_Light_ActionBar = 2131492865;
			
			// aapt resource value: 0x7f0c0003
			public const int Widget_AppCompat_Light_ActionBar_Solid = 2131492867;
			
			// aapt resource value: 0x7f0c0004
			public const int Widget_AppCompat_Light_ActionBar_Solid_Inverse = 2131492868;
			
			// aapt resource value: 0x7f0c0012
			public const int Widget_AppCompat_Light_ActionBar_TabBar = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int Widget_AppCompat_Light_ActionBar_TabBar_Inverse = 2131492883;
			
			// aapt resource value: 0x7f0c0018
			public const int Widget_AppCompat_Light_ActionBar_TabText = 2131492888;
			
			// aapt resource value: 0x7f0c0019
			public const int Widget_AppCompat_Light_ActionBar_TabText_Inverse = 2131492889;
			
			// aapt resource value: 0x7f0c0015
			public const int Widget_AppCompat_Light_ActionBar_TabView = 2131492885;
			
			// aapt resource value: 0x7f0c0016
			public const int Widget_AppCompat_Light_ActionBar_TabView_Inverse = 2131492886;
			
			// aapt resource value: 0x7f0c000c
			public const int Widget_AppCompat_Light_ActionButton = 2131492876;
			
			// aapt resource value: 0x7f0c000e
			public const int Widget_AppCompat_Light_ActionButton_CloseMode = 2131492878;
			
			// aapt resource value: 0x7f0c0010
			public const int Widget_AppCompat_Light_ActionButton_Overflow = 2131492880;
			
			// aapt resource value: 0x7f0c001c
			public const int Widget_AppCompat_Light_ActionMode_Inverse = 2131492892;
			
			// aapt resource value: 0x7f0c0039
			public const int Widget_AppCompat_Light_ActivityChooserView = 2131492921;
			
			// aapt resource value: 0x7f0c0037
			public const int Widget_AppCompat_Light_AutoCompleteTextView = 2131492919;
			
			// aapt resource value: 0x7f0c003b
			public const int Widget_AppCompat_Light_Base_ActionBar = 2131492923;
			
			// aapt resource value: 0x7f0c003d
			public const int Widget_AppCompat_Light_Base_ActionBar_Solid = 2131492925;
			
			// aapt resource value: 0x7f0c003e
			public const int Widget_AppCompat_Light_Base_ActionBar_Solid_Inverse = 2131492926;
			
			// aapt resource value: 0x7f0c0046
			public const int Widget_AppCompat_Light_Base_ActionBar_TabBar = 2131492934;
			
			// aapt resource value: 0x7f0c0047
			public const int Widget_AppCompat_Light_Base_ActionBar_TabBar_Inverse = 2131492935;
			
			// aapt resource value: 0x7f0c004c
			public const int Widget_AppCompat_Light_Base_ActionBar_TabText = 2131492940;
			
			// aapt resource value: 0x7f0c004d
			public const int Widget_AppCompat_Light_Base_ActionBar_TabText_Inverse = 2131492941;
			
			// aapt resource value: 0x7f0c0049
			public const int Widget_AppCompat_Light_Base_ActionBar_TabView = 2131492937;
			
			// aapt resource value: 0x7f0c004a
			public const int Widget_AppCompat_Light_Base_ActionBar_TabView_Inverse = 2131492938;
			
			// aapt resource value: 0x7f0c0040
			public const int Widget_AppCompat_Light_Base_ActionButton = 2131492928;
			
			// aapt resource value: 0x7f0c0042
			public const int Widget_AppCompat_Light_Base_ActionButton_CloseMode = 2131492930;
			
			// aapt resource value: 0x7f0c0044
			public const int Widget_AppCompat_Light_Base_ActionButton_Overflow = 2131492932;
			
			// aapt resource value: 0x7f0c004f
			public const int Widget_AppCompat_Light_Base_ActionMode_Inverse = 2131492943;
			
			// aapt resource value: 0x7f0c0076
			public const int Widget_AppCompat_Light_Base_ActivityChooserView = 2131492982;
			
			// aapt resource value: 0x7f0c0074
			public const int Widget_AppCompat_Light_Base_AutoCompleteTextView = 2131492980;
			
			// aapt resource value: 0x7f0c005e
			public const int Widget_AppCompat_Light_Base_DropDownItem_Spinner = 2131492958;
			
			// aapt resource value: 0x7f0c0066
			public const int Widget_AppCompat_Light_Base_ListPopupWindow = 2131492966;
			
			// aapt resource value: 0x7f0c0060
			public const int Widget_AppCompat_Light_Base_ListView_DropDown = 2131492960;
			
			// aapt resource value: 0x7f0c0068
			public const int Widget_AppCompat_Light_Base_PopupMenu = 2131492968;
			
			// aapt resource value: 0x7f0c005c
			public const int Widget_AppCompat_Light_Base_Spinner = 2131492956;
			
			// aapt resource value: 0x7f0c0025
			public const int Widget_AppCompat_Light_DropDownItem_Spinner = 2131492901;
			
			// aapt resource value: 0x7f0c002a
			public const int Widget_AppCompat_Light_ListPopupWindow = 2131492906;
			
			// aapt resource value: 0x7f0c0027
			public const int Widget_AppCompat_Light_ListView_DropDown = 2131492903;
			
			// aapt resource value: 0x7f0c002c
			public const int Widget_AppCompat_Light_PopupMenu = 2131492908;
			
			// aapt resource value: 0x7f0c0023
			public const int Widget_AppCompat_Light_Spinner_DropDown_ActionBar = 2131492899;
			
			// aapt resource value: 0x7f0c0029
			public const int Widget_AppCompat_ListPopupWindow = 2131492905;
			
			// aapt resource value: 0x7f0c0026
			public const int Widget_AppCompat_ListView_DropDown = 2131492902;
			
			// aapt resource value: 0x7f0c002d
			public const int Widget_AppCompat_ListView_Menu = 2131492909;
			
			// aapt resource value: 0x7f0c002b
			public const int Widget_AppCompat_PopupMenu = 2131492907;
			
			// aapt resource value: 0x7f0c000a
			public const int Widget_AppCompat_ProgressBar = 2131492874;
			
			// aapt resource value: 0x7f0c0009
			public const int Widget_AppCompat_ProgressBar_Horizontal = 2131492873;
			
			// aapt resource value: 0x7f0c0022
			public const int Widget_AppCompat_Spinner_DropDown_ActionBar = 2131492898;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023};
			
			// aapt resource value: 10
			public const int ActionBar_background = 10;
			
			// aapt resource value: 12
			public const int ActionBar_backgroundSplit = 12;
			
			// aapt resource value: 11
			public const int ActionBar_backgroundStacked = 11;
			
			// aapt resource value: 13
			public const int ActionBar_customNavigationLayout = 13;
			
			// aapt resource value: 3
			public const int ActionBar_displayOptions = 3;
			
			// aapt resource value: 9
			public const int ActionBar_divider = 9;
			
			// aapt resource value: 1
			public const int ActionBar_height = 1;
			
			// aapt resource value: 14
			public const int ActionBar_homeLayout = 14;
			
			// aapt resource value: 7
			public const int ActionBar_icon = 7;
			
			// aapt resource value: 16
			public const int ActionBar_indeterminateProgressStyle = 16;
			
			// aapt resource value: 18
			public const int ActionBar_itemPadding = 18;
			
			// aapt resource value: 8
			public const int ActionBar_logo = 8;
			
			// aapt resource value: 2
			public const int ActionBar_navigationMode = 2;
			
			// aapt resource value: 17
			public const int ActionBar_progressBarPadding = 17;
			
			// aapt resource value: 15
			public const int ActionBar_progressBarStyle = 15;
			
			// aapt resource value: 4
			public const int ActionBar_subtitle = 4;
			
			// aapt resource value: 6
			public const int ActionBar_subtitleTextStyle = 6;
			
			// aapt resource value: 0
			public const int ActionBar_title = 0;
			
			// aapt resource value: 5
			public const int ActionBar_titleTextStyle = 5;
			
			public static int[] ActionBarLayout = new int[] {
					16842931};
			
			// aapt resource value: 0
			public const int ActionBarLayout_android_layout_gravity = 0;
			
			public static int[] ActionBarWindow = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int ActionBarWindow_windowActionBar = 0;
			
			// aapt resource value: 1
			public const int ActionBarWindow_windowActionBarOverlay = 1;
			
			// aapt resource value: 6
			public const int ActionBarWindow_windowFixedHeightMajor = 6;
			
			// aapt resource value: 4
			public const int ActionBarWindow_windowFixedHeightMinor = 4;
			
			// aapt resource value: 3
			public const int ActionBarWindow_windowFixedWidthMajor = 3;
			
			// aapt resource value: 5
			public const int ActionBarWindow_windowFixedWidthMinor = 5;
			
			// aapt resource value: 2
			public const int ActionBarWindow_windowSplitActionBar = 2;
			
			public static int[] ActionMenuItemView = new int[] {
					16843071};
			
			// aapt resource value: 0
			public const int ActionMenuItemView_android_minWidth = 0;
			
			public static int[] ActionMenuView;
			
			public static int[] ActionMode = new int[] {
					2130772006,
					2130772010,
					2130772011,
					2130772015,
					2130772017};
			
			// aapt resource value: 3
			public const int ActionMode_background = 3;
			
			// aapt resource value: 4
			public const int ActionMode_backgroundSplit = 4;
			
			// aapt resource value: 0
			public const int ActionMode_height = 0;
			
			// aapt resource value: 2
			public const int ActionMode_subtitleTextStyle = 2;
			
			// aapt resource value: 1
			public const int ActionMode_titleTextStyle = 1;
			
			public static int[] ActivityChooserView = new int[] {
					2130772074,
					2130772075};
			
			// aapt resource value: 1
			public const int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
			
			// aapt resource value: 0
			public const int ActivityChooserView_initialActivityCount = 0;
			
			public static int[] CompatTextView = new int[] {
					2130772077};
			
			// aapt resource value: 0
			public const int CompatTextView_textAllCaps = 0;
			
			public static int[] LinearLayoutICS = new int[] {
					2130772014,
					2130772053,
					2130772054};
			
			// aapt resource value: 0
			public const int LinearLayoutICS_divider = 0;
			
			// aapt resource value: 2
			public const int LinearLayoutICS_dividerPadding = 2;
			
			// aapt resource value: 1
			public const int LinearLayoutICS_showDividers = 1;
			
			public static int[] MenuGroup = new int[] {
					16842766,
					16842960,
					16843156,
					16843230,
					16843231,
					16843232};
			
			// aapt resource value: 5
			public const int MenuGroup_android_checkableBehavior = 5;
			
			// aapt resource value: 0
			public const int MenuGroup_android_enabled = 0;
			
			// aapt resource value: 1
			public const int MenuGroup_android_id = 1;
			
			// aapt resource value: 3
			public const int MenuGroup_android_menuCategory = 3;
			
			// aapt resource value: 4
			public const int MenuGroup_android_orderInCategory = 4;
			
			// aapt resource value: 2
			public const int MenuGroup_android_visible = 2;
			
			public static int[] MenuItem = new int[] {
					16842754,
					16842766,
					16842960,
					16843014,
					16843156,
					16843230,
					16843231,
					16843233,
					16843234,
					16843235,
					16843236,
					16843237,
					16843375,
					2130772045,
					2130772046,
					2130772047,
					2130772048};
			
			// aapt resource value: 14
			public const int MenuItem_actionLayout = 14;
			
			// aapt resource value: 16
			public const int MenuItem_actionProviderClass = 16;
			
			// aapt resource value: 15
			public const int MenuItem_actionViewClass = 15;
			
			// aapt resource value: 9
			public const int MenuItem_android_alphabeticShortcut = 9;
			
			// aapt resource value: 11
			public const int MenuItem_android_checkable = 11;
			
			// aapt resource value: 3
			public const int MenuItem_android_checked = 3;
			
			// aapt resource value: 1
			public const int MenuItem_android_enabled = 1;
			
			// aapt resource value: 0
			public const int MenuItem_android_icon = 0;
			
			// aapt resource value: 2
			public const int MenuItem_android_id = 2;
			
			// aapt resource value: 5
			public const int MenuItem_android_menuCategory = 5;
			
			// aapt resource value: 10
			public const int MenuItem_android_numericShortcut = 10;
			
			// aapt resource value: 12
			public const int MenuItem_android_onClick = 12;
			
			// aapt resource value: 6
			public const int MenuItem_android_orderInCategory = 6;
			
			// aapt resource value: 7
			public const int MenuItem_android_title = 7;
			
			// aapt resource value: 8
			public const int MenuItem_android_titleCondensed = 8;
			
			// aapt resource value: 4
			public const int MenuItem_android_visible = 4;
			
			// aapt resource value: 13
			public const int MenuItem_showAsAction = 13;
			
			public static int[] MenuView = new int[] {
					16842926,
					16843052,
					16843053,
					16843054,
					16843055,
					16843056,
					16843057,
					16843829};
			
			// aapt resource value: 4
			public const int MenuView_android_headerBackground = 4;
			
			// aapt resource value: 2
			public const int MenuView_android_horizontalDivider = 2;
			
			// aapt resource value: 5
			public const int MenuView_android_itemBackground = 5;
			
			// aapt resource value: 6
			public const int MenuView_android_itemIconDisabledAlpha = 6;
			
			// aapt resource value: 1
			public const int MenuView_android_itemTextAppearance = 1;
			
			// aapt resource value: 7
			public const int MenuView_android_preserveIconSpacing = 7;
			
			// aapt resource value: 3
			public const int MenuView_android_verticalDivider = 3;
			
			// aapt resource value: 0
			public const int MenuView_android_windowAnimationStyle = 0;
			
			public static int[] SearchView = new int[] {
					16843039,
					16843296,
					16843364,
					2130772058,
					2130772059};
			
			// aapt resource value: 2
			public const int SearchView_android_imeOptions = 2;
			
			// aapt resource value: 1
			public const int SearchView_android_inputType = 1;
			
			// aapt resource value: 0
			public const int SearchView_android_maxWidth = 0;
			
			// aapt resource value: 3
			public const int SearchView_iconifiedByDefault = 3;
			
			// aapt resource value: 4
			public const int SearchView_queryHint = 4;
			
			public static int[] Spinner = new int[] {
					16842927,
					16843125,
					16843126,
					16843362,
					16843436,
					16843437,
					2130772049,
					2130772050,
					2130772051,
					2130772052};
			
			// aapt resource value: 4
			public const int Spinner_android_dropDownHorizontalOffset = 4;
			
			// aapt resource value: 1
			public const int Spinner_android_dropDownSelector = 1;
			
			// aapt resource value: 5
			public const int Spinner_android_dropDownVerticalOffset = 5;
			
			// aapt resource value: 3
			public const int Spinner_android_dropDownWidth = 3;
			
			// aapt resource value: 0
			public const int Spinner_android_gravity = 0;
			
			// aapt resource value: 2
			public const int Spinner_android_popupBackground = 2;
			
			// aapt resource value: 9
			public const int Spinner_disableChildrenWhenDisabled = 9;
			
			// aapt resource value: 8
			public const int Spinner_popupPromptView = 8;
			
			// aapt resource value: 6
			public const int Spinner_prompt = 6;
			
			// aapt resource value: 7
			public const int Spinner_spinnerMode = 7;
			
			public static int[] Theme = new int[] {
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044};
			
			// aapt resource value: 0
			public const int Theme_actionDropDownStyle = 0;
			
			// aapt resource value: 1
			public const int Theme_dropdownListPreferredItemHeight = 1;
			
			// aapt resource value: 5
			public const int Theme_listChoiceBackgroundIndicator = 5;
			
			// aapt resource value: 4
			public const int Theme_panelMenuListTheme = 4;
			
			// aapt resource value: 3
			public const int Theme_panelMenuListWidth = 3;
			
			// aapt resource value: 2
			public const int Theme_popupMenuStyle = 2;
			
			public static int[] View = new int[] {
					16842970,
					2130772024,
					2130772025};
			
			// aapt resource value: 0
			public const int View_android_focusable = 0;
			
			// aapt resource value: 2
			public const int View_paddingEnd = 2;
			
			// aapt resource value: 1
			public const int View_paddingStart = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
